# docker build -t conjecto/blazegraph:%%BLAZEGRAPH_VERSION%% .
FROM %%JDK_SUITE%%
MAINTAINER Conjecto <contact@conjecto.com>

RUN apk add --no-cache bash
# install blazegraph
ADD %%BLAZEGRAPH_URL%% /usr/bin/blazegraph.jar

RUN mkdir /docker-entrypoint-initdb.d
RUN mkdir /var/lib/blazegraph

# Config files
COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 9999
CMD ["blazegraph"]